-- View: adempiere.rv_orderlinetodeliver

-- DROP VIEW adempiere.rv_orderlinetodeliver;

CREATE OR REPLACE VIEW adempiere.rv_orderlinetodeliver
 AS
 SELECT c_orderline.c_orderline_id,
    c_orderline.ad_client_id,
    c_orderline.ad_org_id,
    c_orderline.isactive,
    c_orderline.created,
    c_orderline.createdby,
    c_orderline.updated,
    c_orderline.updatedby,
    c_orderline.c_order_id,
    c_orderline.line,
    c_orderline.c_bpartner_id,
    c_orderline.c_bpartner_location_id,
    c_orderline.dateordered,
    c_orderline.datepromised,
    c_orderline.datedelivered,
    c_orderline.dateinvoiced,
    c_orderline.description,
    c_orderline.m_product_id,
    c_orderline.m_warehouse_id,
    c_orderline.c_uom_id,
    c_orderline.qtyordered,
    c_orderline.qtyreserved,
    c_orderline.qtydelivered,
    c_orderline.qtyinvoiced,
    c_orderline.m_shipper_id,
    c_orderline.c_currency_id,
    c_orderline.pricelist,
    c_orderline.priceactual,
    c_orderline.pricelimit,
    c_orderline.linenetamt,
    c_orderline.discount,
    c_orderline.freightamt,
    c_orderline.c_charge_id,
    c_orderline.c_tax_id,
    c_orderline.s_resourceassignment_id,
    c_orderline.ref_orderline_id,
    c_orderline.m_attributesetinstance_id,
    c_orderline.isdescription,
    c_orderline.processed,
    c_orderline.qtyentered,
    c_orderline.priceentered,
    c_orderline.c_project_id,
    c_orderline.pricecost,
    c_orderline.qtylostsales,
    c_orderline.c_projectphase_id,
    c_orderline.c_projecttask_id,
    c_orderline.rrstartdate,
    c_orderline.rramt,
    c_orderline.c_campaign_id,
    c_orderline.c_activity_id,
    c_orderline.user1_id,
    c_orderline.user2_id,
    c_orderline.ad_orgtrx_id,
    c_orderline.link_orderline_id,
    c_orderline.pp_cost_collector_id,
    c_orderline.m_promotion_id,
    c_orderline.a_asset_id,
    c_orderline.ismntline,
    c_orderline.nperiod,
    c_orderline.uomperiod,
    c_orderline.issuppline,
    c_orderline.ismaterialincl,
    c_orderline.isresincl,
    c_orderline.bom_orderline_id,
    c_orderline.bom_product_id,
    c_orderline.lit_iscashordadv,
    c_orderline.lit_advperc,
    c_orderline.rsm_tipologia,
    c_orderline.rsm_tipomerce,
    c_orderline.rsm_monofase_id,
    c_orderline.rsm_ritenuta_id,
    c_orderline.rsm_bolli_id,
    c_orderline.rsm_imposta_id,
    c_orderline.paymentrule,
    c_orderline.c_paymentterm_id,
    c_orderline.valorediconversione,
    c_orderline.qtyacquisto,
    c_orderline.prezzocrudo,
    c_orderline.c_uom_cr_id,
    c_orderline.c_uom_crpr_id,
    c_orderline.valdiconvprezzo,
    c_orderline.valdiconvdivprezzo,
    c_orderline.c_contropartita_id,
    c_orderline.cru_tipologiaimbarco,
    c_orderline.cru_eccesso,
    c_orderline.cru_calo,
    c_orderline.m_attributeset_id,
    c_orderline.popolalinee,
    c_orderline.popolalineeatt,
    c_orderline.popolalineeord,
    c_orderline.mfg_orderlinegroup,
    c_orderline.dateeffectivepromised,
    c_orderline.commissionaliq_1,
    c_orderline.commissionval_1,
    c_orderline.commissionaliq_2,
    c_orderline.commissionval_2,
    c_orderline.qtyordered - c_orderline.qtydelivered AS qtytodeliver
   FROM c_orderline;

ALTER TABLE adempiere.rv_orderlinetodeliver
    OWNER TO postgres;

